#### Resuming What i left

In [1]:
import pandas as pd

In [2]:
data = {
    'name':['praveen','Dhanush','Srinu','Kanaka'],
    'city':['Hyd','Hyd','Gondi','Kuwait'],
    'age':[25,23,49,45]
}


df = pd.DataFrame(data)
df

      name    city  age
0  praveen     Hyd   25
1  Dhanush     Hyd   23
2    Srinu   Gondi   49
3   Kanaka  Kuwait   45

In [3]:
df['name']

0    praveen
1    Dhanush
2      Srinu
3     Kanaka
Name: name, dtype: object

In [4]:
df.shape

(4, 3)

In [5]:
df.head(2)

      name city  age
0  praveen  Hyd   25
1  Dhanush  Hyd   23

In [6]:
df.tail(2)

     name    city  age
2   Srinu   Gondi   49
3  Kanaka  Kuwait   45

In [18]:
df['gender'] = ['male','male,','male','female']
df

      name    city  age  gender
0  praveen     Hyd   25    male
1  Dhanush     Hyd   23   male,
2    Srinu   Gondi   49    male
3   Kanaka  Kuwait   45  female

In [13]:
df

      name    city  age  gender
0  praveen     Hyd   25    male
1  Dhanush     Hyd   23   male,
2    Srinu   Gondi   49    male
3   Kanaka  Kuwait   45  famale

In [14]:
df[df['age']>25]

     name    city  age  gender
2   Srinu   Gondi   49    male
3  Kanaka  Kuwait   45  famale

In [20]:
df[(df['age']>25) & (df['gender']=='female')]

     name    city  age  gender
3  Kanaka  Kuwait   45  female

In [21]:
df.sort_values('age',ascending=False)

      name    city  age  gender
2    Srinu   Gondi   49    male
3   Kanaka  Kuwait   45  female
0  praveen     Hyd   25    male
1  Dhanush     Hyd   23   male,

In [23]:
df.sort_values('age',ascending=True)

      name    city  age  gender
1  Dhanush     Hyd   23   male,
0  praveen     Hyd   25    male
3   Kanaka  Kuwait   45  female
2    Srinu   Gondi   49    male

In [24]:
df[['name','city']]

      name    city
0  praveen     Hyd
1  Dhanush     Hyd
2    Srinu   Gondi
3   Kanaka  Kuwait